### ISSUE TITLE
[suggestion] Adding src.filename to process function

### ISSUE THREAD

**Issue by dariuszsikorski** [mgcrea/gulp-concat-util#6]
Hello,

Gulp concat util is exactly what I was looking for to replace gulp-concat and gulp-insert utils, but there is one thing missing for my use case.

I would like to concatenate a lot of files, and the result file should contain names of used partials for concatenation.

Here is an example code with src.filename usage

    gulp.src("./*")
    .pipe(concat('output.scss', {
      process: function(src){
        var result = src.filename + "\n" + src; // example of filename usage
        return result;
      }
    }))
    .pipe(concat.header('Library Header' + "\n"))
    .pipe(gulp.dest("./dist/"));

If you would pay a moment for this case, it would be very useful for improving the build process.

**Comment by EduardJS** [comment]
This is exactly what I was looking for in the past few hours. I ended up using `gulp insert` with `.pipe(insert.transform( function( contents, file ){ ... }))`.

**Comment by EduardJS** [comment]
@dariuszsikorski Decided to do my own fix so here it is: https://github.com/mgcrea/gulp-concat-util/pull/7

Hopefully, @mgcrea will merge this.

**Comment by dariuszsikorski** [comment]
@EduardJS Thank you for your time! I will incorporate it into my project.

**Comment by mgcrea** [comment]
Meged.
